project:
  type: book
  output-dir: _book

book:
  title: "Student Course Services II2100"
  subtitle: "Panduan pengguna dan referensi teknis"
  author: "Tim II2100"
  date: "2026-08-23"
  chapters:
    - index.qmd
    - user-guide.qmd
    - technical-reference.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap

lang: id

